== View Documentation
*Validierung der KPI's noch ausstehend.*  +
*In weiteren Iterationen werden bestehende Views schrittweise erweitert und neue ergänzt!* +

=== 1. `jahrgang_kpi_view`

*Zweck:*  +
Aggregiert alle relevanten Leistungskennzahlen (KPIs) auf Ebene des Jahrgangs.  
Ermöglicht den Vergleich der Studienleistungen zwischen verschiedenen Jahrgängen eines Studiengangs.

*Inhalt / Felder:*  +
- `jahrgang_id` – eindeutige Identifikation des Jahrgangs +  
- `studiengang_id` – Zuordnung zum jeweiligen Studiengang  +
- `anzahl_module` – Gesamtanzahl aller Module im Jahrgang  +
- `anzahl_bestanden` – Anzahl bestandener Module  +
- `bestehensquote` – Verhältnis bestandener zu absolvierten Modulen  +
- `durchfallquote` – Verhältnis nicht bestandener zu absolvierten Modulen  +
- `abschlussquote` – Anteil der Studierenden, die den Studiengang abgeschlossen haben + 


*Code:*
[source, sql]
----
CREATE OR REPLACE VIEW jahrgang_kpi_view AS
SELECT
    s.Jahr,

    COUNT(DISTINCT s.studentID) AS gesamt_anzahl_studierende,

    COUNT(DISTINCT m.Modulnummer) AS gesamt_anzahl_module,

    ROUND(
        100.0 * SUM(CASE WHEN s.Status = 'bestanden' THEN 1 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN s.Status IN ('bestanden', 'nicht bestanden') THEN 1 ELSE 0 END), 0),
        2
    ) AS bestehensquote_prozent,


    ROUND(
        100.0 * SUM(CASE WHEN s.Status = 'nicht bestanden' THEN 1 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN s.Status IN ('bestanden', 'nicht bestanden') THEN 1 ELSE 0 END), 0),
        2
    ) AS durchfallquote_prozent,


    ROUND(
        SUM(CAST(s.Note AS FLOAT) * m.Credits)
        / NULLIF(SUM(CASE WHEN s.Status = 'bestanden' THEN m.Credits ELSE 0 END), 0),
        2
    ) AS durchschnittsnote_gewichtet,


    PERCENTILE_CONT(0.5)
      WITHIN GROUP (ORDER BY CAST(s.Note AS FLOAT))
      FILTER (WHERE s.Status = 'bestanden') AS median_note

FROM students_final.stg_students_with_credits s
JOIN students_final.module m
  ON s.Modulnummer = m.Modulnummer
WHERE s.Status IN ('bestanden', 'nicht bestanden')
GROUP BY s.Jahr
ORDER BY s.Jahr;
----

*Verwendung:*  +
Basis-View für Dashboards mit Jahrgangsvergleichen (z. B. Trendanalysen, Leistungsentwicklung über Zeit). +

*Darstellung:* +
 * Zeitliche Entwicklung der Kennzahlen über mehrere Jahrgänge: +
    - *Liniendiagramm* für die Entwicklung der Bestehensquote im Zeitverlauf   +
    - *Säulendiagramm* für die Anzahl bestandener Module pro Jahrgang  +
  * Diese Ebene ermöglicht Trendanalysen und Prognosen über den Verlauf der Studienergebnisse +

---

=== 2. `studienrichtung_kpi_view`

*Zweck:*  +
Bereitstellung von Kennzahlen auf Ebene der Studienrichtung, um interne Vergleiche innerhalb eines Studiengangs zu ermöglichen.

*Inhalt / Felder:*  +
- `studienrichtung_id` – eindeutige Kennung der Studienrichtung  +
- `studiengang_id` – Zuordnung zur übergeordneten Studienrichtung  +
- `anzahl_module` – Gesamtanzahl der Module in der Studienrichtung  +
- `anzahl_bestanden` – Anzahl bestandener Module  + 
- `bestehensquote` – Anteil bestandener Module an allen belegten Modulen  +
- `durchfallquote` – Anteil nicht bestandener Module  +
- `abschlussquote` – Anteil der abgeschlossenen Studienleistungen je Richtung  +

*Code:*
[source, sql]
----
CREATE OR REPLACE VIEW studienrichtung_kpi_view AS
SELECT
    m.Studienrichtung,

    (
      SELECT COUNT(DISTINCT sc.studentID)
      FROM students_final.stg_students_clean sc
      WHERE sc.Studienrichtung = m.Studienrichtung
    ) AS gesamt_anzahl_studierende,

    
    COUNT(DISTINCT m.Modulnummer) AS gesamt_anzahl_module,


    ROUND(
        100.0 * SUM(CASE WHEN s.Status = 'bestanden' THEN 1 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN s.Status IN ('bestanden', 'nicht bestanden') THEN 1 ELSE 0 END), 0),
        2
    ) AS bestehensquote_prozent,

    
    ROUND(
        100.0 * SUM(CASE WHEN s.Status = 'nicht bestanden' THEN 1 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN s.Status IN ('bestanden', 'nicht bestanden') THEN 1 ELSE 0 END), 0),
        2
    ) AS durchfallquote_prozent,

   
    ROUND(
        SUM(CAST(s.Note AS FLOAT) * m.Credits)
        / NULLIF(SUM(CASE WHEN s.Status = 'bestanden' THEN m.Credits ELSE 0 END), 0),
        2
    ) AS durchschnittsnote_gewichtet,

    PERCENTILE_CONT(0.5)
      WITHIN GROUP (ORDER BY CAST(s.Note AS FLOAT))
      FILTER (WHERE s.Status = 'bestanden') AS median_note

FROM students_final.stg_students_with_credits s
JOIN students_final.module m
  ON s.Modulnummer = m.Modulnummer
WHERE s.Status IN ('bestanden', 'nicht bestanden')
GROUP BY m.Studienrichtung;

----


*Verwendung:*  +
Dient als Grundlage für Detailanalysen und Filterung innerhalb des Dashboards nach Studienrichtung. +

*Darstellung:*
* Vergleichende Darstellung einzelner Studienrichtungen innerhalb des Studiengangs: +
    - *Balkendiagramm* für Bestehens- und Durchfallquoten je Studienrichtung  +
    - *Heatmap*  zur Darstellung von Stärken und Schwächen pro Richtung  +

---

=== 3. `studiengang_kpi_view`

*Zweck:*  +
Zentrale Übersicht aller Kennzahlen auf Ebene des gesamten Studiengangs.  


*Inhalt / Felder:*  +
- `studiengang_id` – eindeutige Kennung des Studiengangs  +
- `anzahl_jahrgaenge` – Anzahl der vorhandenen Jahrgänge im Studiengang  +
- `gesamtmodule` – Summe aller angebotenen Module  +
- `bestandene_module` – Gesamtzahl bestandener Module über alle Jahrgänge  +
- `bestehensquote` – Durchschnittliche Bestehensquote aller Studierenden im Studiengang  +
- `durchfallquote` – Durchschnittliche Durchfallquote  +
- `abschlussquote` – Anteil der Studierenden, die den Studiengang erfolgreich abgeschlossen haben  +


*Code:*
[source, sql]
----
CREATE OR REPLACE VIEW studiengang_kpi_view AS
SELECT
   ´
    COUNT(DISTINCT s.studentID) AS gesamt_anzahl_studierende,

    COUNT(DISTINCT m.Modulnummer) AS gesamt_anzahl_module,

    ROUND(
        100.0 * SUM(CASE WHEN s.Status = 'bestanden' THEN 1 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN s.Status IN ('bestanden', 'nicht bestanden') THEN 1 ELSE 0 END), 0),
        2
    ) AS bestehensquote_prozent,

    ROUND(
        100.0 * SUM(CASE WHEN s.Status = 'nicht bestanden' THEN 1 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN s.Status IN ('bestanden', 'nicht bestanden') THEN 1 ELSE 0 END), 0),
        2
    ) AS durchfallquote_prozent,

    ROUND(
        SUM(CAST(s.Note AS FLOAT) * m.Credits)
        / NULLIF(SUM(CASE WHEN s.Status = 'bestanden' THEN m.Credits ELSE 0 END), 0),
        2
    ) AS durchschnittsnote_gewichtet,

     PERCENTILE_CONT(0.5)
      WITHIN GROUP (ORDER BY CAST(s.Note AS FLOAT))
      FILTER (WHERE s.Status = 'bestanden') AS median_note
    

FROM students_final.stg_students_with_credits s
JOIN students_final.module m
  ON s.Modulnummer = m.Modulnummer
WHERE s.Status IN ('bestanden', 'nicht bestanden');
----

*Verwendung:*  +
Primäre Datenquelle für Management-Dashboards und KPI-Auswertungen. +

*Darstellung:* +
Darstellung als Top KPI's zentral oben auf dem Dashobard, da diese KPI's maximal aggregiert sind! +
Sie solten als großflächige Kacheln oder Infoboxen visualisiert werden mit einer bewertenden Instanz daneben 
(z.B.: Ampel oder Daumen hoch/runter) in Abhängigkeit deren Zielerreichungsgrades. +

---

=== Hinweis zur Architektur

=== 4. student_kpi_view

*Zweck:* +
Aggregiert alle relevanten Studienkennzahlen auf Ebene einzelner Studierender.
Diese View dient als Grundlage für individuelle Leistungsanalysen, Risikoerkennung und Monitoring des Studienfortschritts. +

*Inhalt / Felder:* +

- student_id – eindeutige Identifikation des Studierenden +

- module_gesamt – Anzahl aller belegten Module +

- bestehensrate_je_student – Anteil bestandener Module +

- nichtbestehensrate_je_student – Anteil nicht bestandener Module +

- wiederholungsrate_je_student – Anteil der Module mit mindestens einem Wiederholungsversuch +

*Code:*
[source, sql]
----
CREATE OR REPLACE VIEW student_kpi_view AS
SELECT
student_id,
COUNT(DISTINCT module_id) AS module_gesamt,

ROUND(
    AVG(CASE WHEN passed THEN 1 ELSE 0 END) * 100,
    2
) AS bestehensrate_je_student,

ROUND(
    AVG(CASE WHEN NOT passed THEN 1 ELSE 0 END) * 100,
    2
) AS nichtbestehensrate_je_student,

ROUND(
    SUM(CASE WHEN attempt_number > 1 THEN 1 ELSE 0 END) * 100.0
    / COUNT(*),
    2
) AS wiederholungsrate_je_student

FROM student_results
GROUP BY student_id;
----

*Verwendung:* +
Grundlage für individuelle Leistungsanalysen, Frühwarnsysteme, Lernstandsdiagnostik und Vergleiche innerhalb von Kohorten. +

*Darstellung:* +

Balkendiagramm* für Bestehensrate pro Student +

Radarchart* zur Visualisierung individueller Stärken und Schwächen +

Drilldown-Komponente* von Studiengang → Jahrgang → Student +

=== 5. modul_kpi_view

*Zweck:* +
Bündelt alle Kennzahlen für einzelne Module zur Analyse von Schwierigkeit, Durchfallquoten und Wiederholungsverhalten.
Diese View unterstützt die Identifikation von Bottleneck-Modulen und strukturellen Studienhindernissen. +

*Inhalt / Felder:* +

- modul_id – eindeutige Modulkennung +

- modulname – Klarbezeichnung des Moduls +

- bestehensrate – Anteil bestandener Prüfungsversuche +

- nichtbestehensrate – Anteil nicht bestandener Prüfungsversuche +

- first_try_rate – Erfolgsquote im Erstversuch +

- wiederholungsrate – Anteil der Prüfungen mit mehr als einem Versuch +

- total_students – Anzahl der Studierenden, die das Modul belegt haben +

*Code:*
[source, sql]
----
CREATE OR REPLACE VIEW modul_kpi_view AS
SELECT
f.modulID,
dM.Modulname,

ROUND(
    AVG(CASE WHEN f.bestanden_flag = 1 THEN 1 ELSE 0 END) * 100,
    2
) AS bestehensrate,

ROUND(
    AVG(CASE WHEN f.bestanden_flag = 0 THEN 1 ELSE 0 END) * 100,
    2
) AS nichtbestehensrate,

ROUND(
    SUM(CASE WHEN attempt_number = 1 AND f.bestanden_flag = 1 THEN 1 END) 
    * 100.0 / COUNT(*),
    2
) AS first_try_rate,

ROUND(
    SUM(CASE WHEN attempt_number > 1 THEN 1 END) 
    * 100.0 / COUNT(*),
    2
) AS wiederholungsrate,

COUNT(DISTINCT f.studentID) AS total_students

FROM fact_kpi f
JOIN dim_modul dM
ON f.modulID = dM.modulID
GROUP BY f.modulID, dM.Modulname;
----
*Verwendung:* +
Ideal zur Identifikation von problematischen Modulen, zur Lehrplanung und zur Bewertung des Lernfortschritts innerhalb von Curricula. +

*Darstellung:* +

Top-5 Bottleneck-Module* (Bar Chart) +

Heatmap* (Bestehensrate × Wiederholungsrate) +

Trendanalyse* der Modulperformance über die letzten Jahrgänge +
